### ISSUE TITLE
Melhorias no front-end e parametrização dos parâmetros hard codados

### ISSUE THREAD

**Issue by LukasMeine** [citaralabs/emissor-nota-fiscal#1]

**Comment by rcarvs** [comment]
Poderia descrever um pouco o que espera que seja feito e alguns exemplos? Gostei do projeto e gostaria de contribuir. Na questão dos parâmetros citada

**Comment by LukasMeine** [comment]
Opa @carvs, claro! Então. se você for reparar na requisição que o front end faz, ele envia apenas alguns parâmetros, e todos os outros estão hard codados. A ideia era parametrizar tudo.

**Comment by rcarvs** [comment]
Beleza @LukasMeine! Vou dar um fork e tentar aqui mais tarde! Vamos nos falando. Valeu.

**Comment by igorocampos** [comment]
Aproveitando ainda este issue.

Dei uma olhada no projeto, e entendi que o objetivo é simplificar o maximo possível a emissão de NFe que é feita através do [Sped-nfe](https://github.com/nfephp-org/sped-nfe), certo?

Talvez a complexidade da coisa se dá pela alta gama de possibilidades ao emitir uma NFe. Por exemplo: 
- É combustivel, Arma ou medicamento? (terá tags a mais no XML)
- É venda para não contribuinte interestadual? (tem regras diferente no preenchimento do XML)
- É operação com exterior?
- É uma NFe de importação?

Enfim, talvez definir o escopo a que se quer atender vai facilitar na simplificação. Caso contrario você vai acabar tendo um front-end SUPER complexo e cheio de parametros, passando então a complexidade de preenchimento para o usuario (no front) no lugar do programador (na utilização do Sped-nfe).

**Comment by LukasMeine** [comment]
Opa @igorocampos, exatamente. Alias, concordo contigo a respeito do front end. Talvez um mega exemplo com todos os parametros possiveis nao seja a melhor opcao. Uma boa alternativa seria criar uma pasta de exemplos com alguns front ends diferentes, adaptados pra situacoes diversas.

**Comment by igorocampos** [comment]
OK, posso ajudar, você gostaria de definir alguns tipos de situações que se deseja (talvez a partir das mais simples) ?

Inclusive acho que seria interessante se fosse aberto 1 issue para cada uma, especificando o que espera (quais parametros devem existir no front-end) em cada situação.

**Comment by LukasMeine** [comment]
Honestamente eu to sem muitas ideias, mas eu acho que um exemplo para e-commerce seria algo que atenderia muita gente :D

Talvez um e-commerce de venda de roupas ou algo assim?

**Comment by igorocampos** [comment]
OK, então uma NFe de venda de roupas para PF, podendo ser estadual ou interestadual, com multiplos produtos (roupas) na mesma NFe.

É isso?

**Comment by LukasMeine** [comment]
Acho que é um ponto de partida excelente :D

**Comment by igorocampos** [comment]
@LukasMeine, fiz a PR #8 Dá uma olhada nela no momento, e veja se é isso mesmo que você estava querendo, daqui pra frente o numero de campos vai começar a aumentar bastante ao dar continuidade na PR.

**Comment by LukasMeine** [comment]
Top! Vou dar uma olhadinha assim que chegar em casa.

**Comment by LukasMeine** [comment]
Dei uma olhada no código, é exatamente isso! Retirar o que estiver hardcodado e colocar no front end. Ansioso pra revisar o pull request assim que estiver pronto :D

**Comment by igorocampos** [comment]
No meio do processo abri 2 issues e já enviei 2 PR que corrigem as mesmas. Se puder já fazer o review, seria bom tê-las no master antes do término desta do frontend. Assim poderia já utiliza-las

**Comment by LukasMeine** [comment]
Ambas aprovadas, valeu!

**Comment by LukasMeine** [comment]
Imagino que ja podemos fechar essa issue. Valeu!
